image: ubuntu:latest
stages:
  - deploy
deploy_QA:
  stage: deploy
  only:
    - tags
    - master
  environment: 
    name: Staging
    url: "$QA_URL"
  before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - ssh -o StrictHostKeyChecking=no lukasekmoucka0@"$QA_SERVER" "cd /var/www/html/voidlanguages && git pull"
